import React, { useState, useEffect } from 'react';
import { BookOpen, User, Target, Zap, Clock, Tv, Mic, Droplet, Layers, CheckCircle, ArrowRight, ArrowLeft, Lightbulb, BarChart3, Youtube, Book, MousePointerClick, Brain } from 'lucide-react';

// --- Hardcoded JSON Data (from edujoy.json) ---
// In a real app, this would be fetched or generated by the AI
const learningData = {
  "profile_summary": {
    "goal": "Upgrade career growth in Product Design (UI/UX)",
    "current_level": "Intermediate",
    "focus_area": "Product Design (UI/UX)",
    "session_duration": "20 Minutes",
    "best_learning_time": "Morning",
    "learning_pace": "Slow",
    "content_preference": "Audio Visual"
  },
  "learning_path": [
    {
      "module_number": 1,
      "module_title": "Mastering Advanced UX Research & Strategy",
      "duration": "Week 1-2 (10-14 days)",
      "objective": "Deepen your understanding of qualitative and quantitative research methods, learn to derive strategic insights, and influence product decisions based on data. This moves beyond basic user interviews to more robust research practices.",
      "resources": [
        {
          "type": "YouTube",
          "name": "User Research Methods & Best Practices",
          "link": "https://www.youtube.com/watch?v=Fj-2tVw0d1g",
          "duration_estimate": "~10 minutes per segment (watch in 2-3 daily chunks)",
          "rationale": "This Nielsen Norman Group video breaks down various research methods with clear explanations and visual examples, perfect for a slow, audio-visual learner. Focus on understanding when and why to use each method."
        },
        {
          "type": "Course",
          "name": "Conducting UX Research (Coursera)",
          "link": "https://www.coursera.org/learn/ux-research-google",
          "platform": "Coursera (Google UX Design Professional Certificate)",
          "duration_estimate": "Aim for 20 minutes daily; self-paced. Complete 1-2 lessons per week.",
          "rationale": "Provides a structured, in-depth look at the entire UX research process. As an intermediate learner, focus on the nuances of planning, conducting, and analyzing research to extract actionable insights."
        },
        {
          "type": "Practice",
          "name": "Research Review & Critique",
          "details": "Identify a well-known app or website. For the next few days, dedicate 5-10 minutes of your session to analyzing its features. What research methods do you think they used? How could you validate or invalidate a recent feature change with a specific research method? Document your thoughts."
        }
      ]
    },
    {
      "module_number": 2,
      "module_title": "Elevating UI Design & Interaction Patterns",
      "duration": "Week 3-4 (10-14 days)",
      "objective": "Refine your UI design skills, focusing on advanced visual hierarchy, accessibility best practices, and understanding complex interaction patterns and design systems.",
      "resources": [
        {
          "type": "YouTube",
          "name": "A Beginner's Guide to Design Systems",
          "link": "https://www.youtube.com/watch?v=kYJjY8vQ62Y",
          "duration_estimate": "~15 minutes (watch the full video and re-watch sections slowly)",
          "rationale": "Design systems are crucial for career growth in UI/UX. This video provides a clear, visual introduction, helping you understand the 'why' and 'how' of creating scalable, consistent UI."
        },
        {
          "type": "Course",
          "name": "UX Design: Accessibility",
          "link": "https://www.linkedin.com/learning/ux-design-accessibility",
          "platform": "LinkedIn Learning",
          "duration_estimate": "20 minutes daily (approx. 1 week to complete the full 1h 30m course)",
          "rationale": "Accessibility is no longer a 'nice-to-have' but a fundamental skill. This course offers practical, visual guidance on designing inclusive experiences, a key differentiator for career advancement."
        },
        {
          "type": "Practice",
          "name": "UI Pattern Dissection",
          "details": "Choose a complex UI pattern (e.g., a multi-step form, a data table with filters, a calendar picker). Spend 10 minutes daily analyzing 2-3 examples from popular apps. How do they handle states, feedback, and accessibility? Sketch out improvements."
        }
      ]
    },
    {
      "module_number": 3,
      "module_title": "Crafting Compelling Portfolio Case Studies",
      "duration": "Week 5-6 (10-14 days)",
      "objective": "Learn to articulate your design process, decisions, and impact through compelling case studies that showcase your problem-solving abilities and strategic thinking. This is critical for career progression.",
      "resources": [
        {
          "type": "YouTube",
          "name": "How To Write A Great UX Case Study",
          "link": "https://www.youtube.com/watch?v=wX-y59J-gQ8",
          "duration_estimate": "~16 minutes (watch once, then re-watch specific sections daily for deeper understanding)",
          "rationale": "This video offers practical advice and a structured approach to writing impactful UX case studies, which are your primary tool for impressing hiring managers and securing better roles."
        },
        {
          "type": "Article/Tutorial",
          "name": "The Ultimate Guide to Creating a UX Portfolio",
          "link": "https://www.careerfoundry.com/en/blog/ux-design/how-to-create-a-ux-portfolio-guide/",
          "platform": "CareerFoundry Blog",
          "duration_estimate": "Skim key sections at own pace",
          "rationale": "While you prefer audio-visual, this article complements the video by offering detailed examples and sections to include in a strong portfolio, useful for a slow learner to absorb at their own pace."
        },
        {
          "type": "Practice",
          "name": "Case Study Outline & Storytelling",
          "details": "Select one of your existing projects. Over several days, dedicate your 20 minutes to outlining its case study. Focus on the problem, your process, your unique contributions, the challenges, and the impact of your design. Start drafting compelling headlines for each section."
        }
      ]
    },
    {
      "module_number": 4,
      "module_title": "Effective Collaboration & Stakeholder Management",
      "duration": "Week 7-8 (10-14 days)",
      "objective": "Enhance your communication, presentation, and collaboration skills, learning to effectively manage stakeholders and articulate design rationale within cross-functional teams.",
      "resources": [
        {
          "type": "YouTube",
          "name": "How to Present Your UX Designs to Stakeholders",
          "link": "https://www.youtube.com/watch?v=F0S02QY13B8",
          "duration_estimate": "~11 minutes (watch and take notes on key presentation strategies)",
          "rationale": "Successfully presenting your designs and backing them with strong rationale is vital for influence and career growth. This video offers practical tips on engaging stakeholders."
        },
        {
          "type": "Course",
          "name": "Becoming an Effective Communicator",
          "link": "https://www.linkedin.com/learning/becoming-an-effective-communicator",
          "platform": "LinkedIn Learning",
          "duration_estimate": "20 minutes daily (approx. 5 days to complete the full 1h course)",
          "rationale": "Strong communication underpins all aspects of career growth. This course provides actionable strategies to improve verbal and non-verbal communication, crucial for interacting with product managers, engineers, and leadership."
        },
        {
          "type": "Practice",
          "name": "Design Critique & Feedback Loop",
          "details": "Observe a recent team meeting or design critique. For 10 minutes, reflect on how feedback was given and received. How could you apply active listening techniques? How would you present a contentious design decision more effectively?"
        }
      ]
    },
    {
      "module_number": 5,
      "module_title": "Interview Strategies & Career Advancement",
      "duration": "Week 9-10 (10-14 days)",
      "objective": "Prepare for intermediate-to-senior level UI/UX interviews, understand negotiation tactics, and strategically plan your next career moves.",
      "resources": [
        {
          "type": "YouTube",
          "name": "UX Interview Tips (from a Google Recruiter)",
          "link": "https://www.youtube.com/watch?v=9gWzP0zU8z8",
          "duration_estimate": "~10 minutes (watch and list key takeaways for common interview questions)",
          "rationale": "Direct insights from a recruiter can guide your preparation, helping you understand what hiring managers look for in intermediate to senior roles."
        },
        {
          "type": "YouTube",
          "name": "Product Design Interview: Portfolio Walkthrough",
          "link": "https://www.youtube.com/watch?v=vVj_Qx-2B-c",
          "duration_estimate": "~17 minutes (watch how a candidate presents their work and critically analyze their approach)",
          "rationale": "A portfolio walkthrough is often the core of a product design interview. This video demonstrates how to articulate your work effectively, which is vital for securing better roles."
        },
        {
          "type": "Practice",
          "name": "Mock Portfolio Presentation",
          "details": "Record yourself (even just audio) for 10 minutes presenting one of your key portfolio case studies. Listen back and identify areas for improvement in clarity, storytelling, and impact. Repeat daily until you feel confident."
        }
      ]
    }
  ],
  "action_plan": {
    "quick_start": "Begin with Module 1 this week. Commit to watching the first YouTube video, even if it's in two 10-minute segments. Immediately start reflecting on the practice activity.",
    "daily_routine": "Set an alarm for 20 minutes each morning. Use the first 5-10 minutes to review notes or outline today's focus. Dedicate the next 10-15 minutes to a resource, pausing as needed. The final 5 minutes should be for quick notes or planning the next day's segment.",
    "progress_tracking": "Keep a simple journal (digital or physical). After each 20-minute session, quickly jot down: 'What did I learn today?' and 'What's my next step?'"
  },
  "pro_tips": [
    "**Embrace the 'Slow' Pace**: Don't rush! Take detailed notes, re-watch segments, and truly internalize the concepts. Quality over quantity in your daily 20 minutes.",
    "**Consistency is Key**: 20 minutes every morning, without fail, will yield far greater results than sporadic long sessions. Build this into a non-negotiable part of your morning routine.",
    "**Active Learning**: Don't just consume. Pause videos, try out concepts in Figma/Sketch, critique existing designs, and actively engage with the material. This will solidify your learning and accelerate growth."
  ],
  "expected_timeline": {
    "to_proficiency": "With consistent 20-minute daily sessions focusing on these modules, you can expect to feel significantly more confident and proficient in advanced UI/UX concepts and career strategies within **2.5 to 3 months**.",
    "milestones": [
      "**Month 1**: Strong grasp of advanced UX research methodologies and strategic application. Enhanced UI skills, particularly in accessibility and early design systems thinking.",
      "**Month 2**: A refined portfolio with at least one compelling case study ready for review, showcasing your process and impact. Improved understanding of presenting designs.",
      "**Month 3**: Confident in stakeholder management, effective communication, and well-prepared for senior-level interviews with a clear career advancement strategy."
    ]
  }
};

// --- Main App Component ---
export default function App() {
  const [screen, setScreen] = useState('onboarding'); // onboarding, loading, dashboard
  const [currentView, setCurrentView] = useState('learn'); // learn, profile
  const [selectedModule, setSelectedModule] = useState(null);

  // Form state
  const [formData, setFormData] = useState({
    name: 'Jane Doe',
    email: 'jane.doe@example.com',
    duration: '20 minutes a day',
    learningStyle: 'slow',
    preferredContent: 'audioVisual',
    categories: ['productDesign', 'uiux'],
    learningGoals: 'update career growth',
    currentState: 'intermediate'
  });

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    if (type === 'checkbox') {
      setFormData(prev => ({
        ...prev,
        categories: checked
          ? [...prev.categories, value]
          : prev.categories.filter(item => item !== value)
      }));
    } else {
      setFormData(prev => ({ ...prev, [name]: value }));
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setScreen('loading');
    // Simulate AI analysis time
    setTimeout(() => {
      setScreen('dashboard');
    }, 2500);
  };

  const renderScreen = () => {
    switch (screen) {
      case 'onboarding':
        return <OnboardingForm formData={formData} setFormData={setFormData} handleInputChange={handleInputChange} handleSubmit={handleSubmit} />;
      case 'loading':
        return <LoadingScreen />;
      case 'dashboard':
        if (selectedModule) {
          return <ModuleDetailScreen module={selectedModule} onBack={() => setSelectedModule(null)} />;
        }
        return <Dashboard currentView={currentView} setCurrentView={setCurrentView} data={learningData} onModuleSelect={setSelectedModule} />;
      default:
        return <OnboardingForm formData={formData} setFormData={setFormData} handleInputChange={handleInputChange} handleSubmit={handleSubmit} />;
    }
  };

  return (
    <div className="font-sans antialiased bg-gray-100" style={{ fontFamily: '"Inter", sans-serif' }}>
      <div className="relative w-full max-w-md mx-auto min-h-screen bg-white shadow-2xl overflow-hidden">
        {renderScreen()}
        {screen === 'dashboard' && !selectedModule && (
          <BottomNav currentView={currentView} setCurrentView={setCurrentView} />
        )}
      </div>
    </div>
  );
}

// --- Screens & Components ---

function OnboardingForm({ formData, handleInputChange, handleSubmit }) {
  return (
    <div className="p-6 pt-10 animate-fadeIn">
      <h1 className="text-3xl font-bold text-gray-900">Welcome!</h1>
      <p className="text-gray-600 mt-2 mb-6">Tell us about your learning goals.</p>
      
      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700">Name</label>
          <input
            type="text"
            name="name"
            value={formData.name}
            onChange={handleInputChange}
            className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
            required
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700">Learning Goals</label>
          <input
            type="text"
            name="learningGoals"
            value={formData.learningGoals}
            onChange={handleInputChange}
            className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
            required
          />
        </div>
        
        <div>
          <label className="block text-sm font-medium text-gray-700">Current Skill</label>
          <select
            name="currentState"
            value={formData.currentState}
            onChange={handleInputChange}
            className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 bg-white"
          >
            <option value="beginner">Beginner</option>
            <option value="intermediate">Intermediate</option>
            <option value="advanced">Advanced</option>
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700">Learning Style</label>
          <select
            name="learningStyle"
            value={formData.learningStyle}
            onChange={handleInputChange}
            className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 bg-white"
          >
            <option value="slow">Slow & Steady</option>
            <option value="moderate">Moderate Pace</option>
            <option value="fast">Fast Paced</option>
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700">Preferred Content</label>
          <select
            name="preferredContent"
            value={formData.preferredContent}
            onChange={handleInputChange}
            className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 bg-white"
          >
            <option value="audioVisual">Audio Visual</option>
            <option value="reading">Reading</option>
            <option value="interactive">Interactive</option>
          </select>
        </div>

        <button
          type="submit"
          className="w-full bg-green-500 text-white font-bold py-3 px-4 rounded-lg shadow-lg hover:bg-green-600 transition-all duration-200 transform hover:scale-105"
        >
          Generate My Learning Plan
        </button>
      </form>
    </div>
  );
}

function LoadingScreen() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-indigo-600 text-white p-6">
      <div className="relative w-24 h-24">
        <div className="absolute inset-0 bg-white opacity-20 rounded-full animate-ping"></div>
        <div className="relative w-24 h-24 bg-white rounded-full flex items-center justify-center shadow-2xl">
          <Brain className="w-12 h-12 text-indigo-600 animate-pulse" />
        </div>
      </div>
      <h2 className="text-2xl font-bold mt-8">Analyzing your goals...</h2>
      <p className="text-lg text-indigo-100 mt-2 text-center">Crafting your personalized learning journey!</p>
    </div>
  );
}

function Dashboard({ currentView, setCurrentView, data, onModuleSelect }) {
  const renderView = () => {
    switch (currentView) {
      case 'learn':
        return <LearningPathScreen data={data} onModuleSelect={onModuleSelect} />;
      case 'profile':
        return <ProfileScreen data={data.profile_summary} />;
      case 'tips':
        return <ProTipsScreen data={data.pro_tips} />;
      default:
        return <LearningPathScreen data={data} onModuleSelect={onModuleSelect} />;
    }
  };

  return <div className="pb-20">{renderView()}</div>;
}

function LearningPathScreen({ data, onModuleSelect }) {
  return (
    <div className="p-6 animate-fadeIn">
      <header className="mb-6">
        <p className="text-lg font-semibold text-green-600">Your Learning Path</p>
        <h1 className="text-3xl font-bold text-gray-900">Product Design & UI/UX</h1>
      </header>
      
      <ActionPlanCard plan={data.action_plan} />
      
      <div className="mt-8">
        <h2 className="text-xl font-bold mb-4 text-gray-800">Your Modules</h2>
        <div className="relative pl-6 border-l-4 border-dashed border-gray-200">
          {data.learning_path.map((module, index) => (
            <ModuleNode
              key={module.module_number}
              module={module}
              onSelect={() => onModuleSelect(module)}
              isLast={index === data.learning_path.length - 1}
            />
          ))}
        </div>
      </div>
    </div>
  );
}

function ModuleNode({ module, onSelect, isLast }) {
  return (
    <div className="mb-10">
      <div className="absolute -left-5 w-8 h-8 bg-green-500 rounded-full border-4 border-white flex items-center justify-center shadow">
        <CheckCircle className="w-4 h-4 text-white" />
      </div>
      <button
        onClick={onSelect}
        className="w-full text-left p-5 bg-white rounded-xl shadow-lg border border-gray-100 hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1"
      >
        <div className="flex justify-between items-center mb-2">
          <span className="text-xs font-semibold uppercase text-indigo-500">
            Module {module.module_number}
          </span>
          <span className="text-xs font-medium text-gray-500">{module.duration}</span>
        </div>
        <h3 className="text-lg font-bold text-gray-900">{module.module_title}</h3>
      </button>
      {!isLast && <div className="absolute left-0 h-10 w-4 -ml-2.5 ">{/* Connector line part */}</div>}
    </div>
  );
}

function ModuleDetailScreen({ module, onBack }) {
  const getIcon = (type) => {
    switch (type.toLowerCase()) {
      case 'youtube': return <Youtube className="w-5 h-5 text-red-500" />;
      case 'course': return <BookOpen className="w-5 h-5 text-blue-500" />;
      case 'practice': return <MousePointerClick className="w-5 h-5 text-green-500" />;
      case 'article/tutorial': return <Book className="w-5 h-5 text-purple-500" />;
      default: return <Layers className="w-5 h-5 text-gray-400" />;
    }
  };

  return (
    <div className="p-6 pt-10 animate-fadeIn">
      <button onClick={onBack} className="flex items-center text-indigo-600 font-semibold mb-4 group">
        <ArrowLeft className="w-5 h-5 mr-2 transition-transform duration-200 group-hover:-translate-x-1" />
        Back to Path
      </button>

      <span className="text-sm font-semibold uppercase text-indigo-500">Module {module.module_number}</span>
      <h1 className="text-3xl font-bold text-gray-900 mt-1">{module.module_title}</h1>
      <p className="text-gray-600 mt-2 mb-6">{module.objective}</p>

      <div className="bg-indigo-50 p-4 rounded-lg mb-6">
        <div className="flex items-center">
          <Clock className="w-5 h-5 text-indigo-600 mr-3" />
          <span className="text-sm font-medium text-indigo-800">Duration: {module.duration}</span>
        </div>
      </div>

      <h2 className="text-xl font-bold mb-4 text-gray-800">Resources</h2>
      <div className="space-y-4">
        {module.resources.map((resource, index) => (
          <a
            key={index}
            href={resource.link}
            target="_blank"
            rel="noopener noreferrer"
            className="block p-4 bg-white rounded-lg shadow border border-gray-100 hover:shadow-md transition-shadow duration-200"
          >
            <div className="flex items-center mb-2">
              {getIcon(resource.type)}
              <span className="ml-2 text-sm font-bold uppercase text-gray-500">{resource.type}</span>
            </div>
            <h4 className="font-semibold text-gray-900">{resource.name}</h4>
            <p className="text-sm text-gray-600 mt-1">{resource.rationale}</p>
            <div className="flex justify-between items-center mt-3">
              <span className="text-xs text-gray-500">{resource.platform || resource.duration_estimate}</span>
              <ArrowRight className="w-4 h-4 text-indigo-500" />
            </div>
          </a>
        ))}
      </div>
    </div>
  );
}

function ActionPlanCard({ plan }) {
  return (
    <div className="bg-gradient-to-br from-indigo-500 to-indigo-700 text-white p-5 rounded-xl shadow-xl">
      <div className="flex items-center mb-3">
        <Zap className="w-6 h-6 mr-3" />
        <h3 className="text-xl font-bold">Your Action Plan</h3>
      </div>
      <ul className="space-y-2 list-disc list-inside text-indigo-100">
        <li><strong>Quick Start:</strong> {plan.quick_start}</li>
        <li><strong>Daily Routine:</strong> {plan.daily_routine}</li>
        <li><strong>Tracking:</strong> {plan.progress_tracking}</li>
      </ul>
    </div>
  );
}

function ProTipsScreen({ data }) {
  return (
    <div className="p-6 animate-fadeIn">
      <h1 className="text-3xl font-bold text-gray-900 mb-6">Pro Tips</h1>
      <div className="space-y-4">
        {data.map((tip, index) => (
          <div key={index} className="bg-yellow-50 border border-yellow-200 p-4 rounded-lg flex items-start">
            <Lightbulb className="w-5 h-5 text-yellow-500 mr-3 mt-1 flex-shrink-0" />
            <p className="text-gray-800" dangerouslySetInnerHTML={{ __html: tip.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') }}></p>
          </div>
        ))}
      </div>
    </div>
  );
}

function ProfileScreen({ data }) {
  const profileItems = [
    { icon: Target, label: "Main Goal", value: data.goal },
    { icon: BarChart3, label: "Current Level", value: data.current_level },
    { icon: Layers, label: "Focus Area", value: data.focus_area },
    { icon: Clock, label: "Session Time", value: data.session_duration },
    { icon: Droplet, label: "Learning Pace", value: data.learning_pace },
    { icon: Tv, label: "Content", value: data.content_preference },
  ];

  return (
    <div className="p-6 animate-fadeIn">
      <div className="flex flex-col items-center mb-6">
        <div className="w-24 h-24 rounded-full bg-indigo-500 text-white flex items-center justify-center text-4xl font-bold shadow-lg mb-3">
          JD
        </div>
        <h2 className="text-2xl font-bold text-gray-900">Jane Doe</h2>
        <p className="text-gray-600">jane.doe@example.com</p>
      </div>

      <div className="bg-gray-50 p-4 rounded-lg">
        <h3 className="text-lg font-bold text-gray-800 mb-4">Your Learning Profile</h3>
        <div className="space-y-3">
          {profileItems.map((item, index) => (
            <div key={index} className="flex items-center">
              <item.icon className="w-5 h-5 text-indigo-500 mr-3" />
              <div>
                <span className="text-xs text-gray-500">{item.label}</span>
                <p className="font-semibold text-gray-900">{item.value}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function BottomNav({ currentView, setCurrentView }) {
  const navItems = [
    { id: 'learn', label: 'Learn', icon: BookOpen },
    { id: 'profile', label: 'Profile', icon: User },
    { id: 'tips', label: 'Pro Tips', icon: Lightbulb },
  ];

  return (
    <div className="absolute bottom-0 left-0 w-full bg-white border-t border-gray-200 shadow-inner">
      <div className="flex justify-around items-center h-16">
        {navItems.map((item) => (
          <button
            key={item.id}
            onClick={() => setCurrentView(item.id)}
            className={`flex flex-col items-center justify-center w-full h-full ${
              currentView === item.id ? 'text-green-500' : 'text-gray-400'
            } transition-colors duration-200`}
          >
            <item.icon className="w-6 h-6" />
            <span className="text-xs font-medium mt-1">{item.label}</span>
          </button>
        ))}
      </div>
    </div>
  );
}